# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: KA-FAI YIP
subtitle: "linguistics & cats"
email: kafai.yip@yale.edu
description: >- # this means to ignore newlines until "baseurl:"
  I am a first-year PhD student in the Department of Linguistics at Yale University.
  I am interested in Syntax and Semantics and their interfaces.
  Cats are my favorite.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true
logo: "/assets/images/88x88.png"
masthead_title: "My Custom Title"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 0 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
breadcrumbs: true  # disabled by default

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ka-Fai Yip 葉家煇"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "linguistics & cats."
  links:
    - label: "kafai.yip@yale.edu"
      icon: "fas fa-fw fa-envelope"
      url: ""
    - label: "Researchgate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Ka_Fai_Yip2"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com.hk/citations?user=XavAwJYAAAAJ&hl=zh-TW&authuser=1"
    - label: "Yale Linguistics"
      icon: "fab fa-fw fa-link"
      url: "https://ling.yale.edu/"

footer:
  links:
    - label: "kafai.yip@yale.edu"
      icon: "fas fa-fw fa-envelope"
      url: ""
    - label: "Researchgate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Ka_Fai_Yip2"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com.hk/citations?user=XavAwJYAAAAJ&hl=zh-TW&authuser=1"
    - label: "Yale Linguistics"
      icon: "fab fa-fw fa-link"
      url: "https://ling.yale.edu/"


defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "mint"
